name: V2 Build Blog-only

on:
  pull_request:
    branches:
      - master
    paths:
      - 'website-1.x/blog/**'
      - 'packages/docusaurus/**'

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Installation
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - name: Build blog-only
        run: yarn workspace docusaurus-2-website build:blogOnly
