name: V2 Windows Tests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'website-1.x/**'
      - 'packages/docusaurus-1.x/**'
      - 'packages/docusaurus-init-1.x/**'

jobs:
  build:
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        run: yarn || yarn || yarn # 3 attempts to avoid timeout errors...
      - name: Docusaurus Jest Tests
        run: yarn test
      - name: Docusaurus Build
        run: yarn build:v2 --locale en
        env:
          CI: true
