name: Coveralls

on: ["push", "pull_request"]

jobs:
  mobx:
    name: Packages coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Build packages
        run: yarn lerna run build:test

      - name: Run Coverage
        run: yarn coverage

      - name: Upload to coveralls
        uses: coverallsapp/github-action@v1.1.2 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
